import { randomUUID } from 'node:crypto';

/**
 * Media storage key generation (docs/DATABASE.md §7.25 `storage_path`,
 * docs/AI-AGENT-RULES.md §29 "Media Rules", docs/DEVELOPMENT-ROADMAP.md
 * Phase 13 "Storage Structure").
 *
 * The documented storage organization is tenant-prefixed:
 *
 *   {store_id}/products/
 *   {store_id}/categories/
 *   {store_id}/cms/
 *   {store_id}/branding/
 *
 * The generic upload endpoint (POST /api/v1/media) creates an asset that is
 * not yet attached to any product / category / page / branding, so no
 * documented subfolder applies to it yet. The key therefore is:
 *
 *   {store_id}/{media_id}
 *
 * which keeps the mandatory store prefix (Store A can never address Store B's
 * objects — tenant isolation at the object level) and yields a unique,
 * predictable object key per asset.
 *
 * OPEN DECISION — subfolder placement for purpose-specific uploads is not
 * defined by the API-SPEC (see the phase report).
 */
export function buildStorageKey(storeId: string, mediaId: string): string {
  return `${storeId}/${mediaId}`;
}

/**
 * Generates the server-side media id. The id is generated by the application
 * (not by the database) so the storage object key can be derived from it
 * before the binary is uploaded; the same id is then used for the metadata
 * row. It is server-generated — never client input.
 */
export function generateMediaId(): string {
  return randomUUID();
}
