import { IsNotEmpty, IsOptional, IsString, Matches, MaxLength } from 'class-validator';

/**
 * POST /api/v1/onboarding/merchant request body (Phase 17 — merchant
 * onboarding).
 *
 * Registers the application-level merchant:
 *
 *   - `firstName` / `lastName`  -> the application `users` row (NOT NULL,
 *                                  docs/DATABASE.md §7.1). Supabase Auth remains
 *                                  responsible for the password/credentials.
 *   - `storeName`               -> the merchant's Store (tenant boundary).
 *   - `slug`                    -> optional storefront slug. When omitted the
 *                                  backend derives one from `storeName` using
 *                                  the documented slug rule (store-slug.ts).
 *   - `currency`                -> optional ISO 4217 code; defaults to EGP.
 *
 * Passwords are NEVER accepted here — authentication is exclusively Supabase
 * Auth's concern.
 */
export class CreateMerchantDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  firstName!: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  lastName!: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  storeName!: string;

  /** Optional storefront slug; validated/generated by the domain layer. */
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  @MaxLength(63)
  slug?: string;

  /** ISO 4217 currency code (char(3)); defaults to EGP. */
  @IsOptional()
  @IsString()
  @Matches(/^[A-Za-z]{3}$/, {
    message: 'currency must be a 3-letter ISO 4217 code (e.g. EGP).',
  })
  currency?: string;
}
